name = "JLDispense"
uuid = "28701581-07d5-413d-9a85-4457ef9ac05e"
authors = ["Ben David <66976120+bmdavid2@users.noreply.github.com>"]
version = "0.1.0"

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Gurobi = "2e9cd046-0924-5485-92f1-d5272153d98b"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
JLIMS = "40aca73e-78db-4064-9398-4788728e7bb7"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
JensenLabDatabase = "0b3b37c8-6757-476c-9f5a-5ef58dc96e5d"
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
RandomProtocolNames = "7e599a7a-9aa2-4e40-a313-4e947a18035e"
SHA = "ea8e919c-243c-51af-8825-aaa63cd721ce"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"
