name = "JLDispense"
uuid = "28701581-07d5-413d-9a85-4457ef9ac05e"
authors = ["Ben David <66976120+bmdavid2@users.noreply.github.com>"]
version = "0.1.0"

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Gurobi = "2e9cd046-0924-5485-92f1-d5272153d98b"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
JLIMS = "40aca73e-78db-4064-9398-4788728e7bb7"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
SHA = "ea8e919c-243c-51af-8825-aaa63cd721ce"
TextWrap = "b718987f-49a8-5099-9789-dcd902bef87d"
UUIDs = "cf7118a7-6976-5b1a-9a39-7adc72f591a4"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"
UnitfulParsableString = "06c00241-927a-4d5b-bb5e-6b5a2ada3567"
